#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash
echo "PID, along with the process name, of processes whose\n"

pgrep -l bash
