#!/usr/bin/env bash
# this script displays To infinity and beyond indefinitely, With a sleep 2 in between each iteration, I am invincible!!! when receiving a SIGTERM signal


#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely

while :
do
echo "I am invincible!!!"
sleep 2
done
